import { CommandMenu, NavBarr } from '@/components'
import './globals.css'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: { children: ReactNode }) {
  return (
    <html lang='en' className='dark'>
      <body>
        <CommandMenu />
        <NavBarr />
        {children}
      </body>
    </html>
  )
}
